### ISSUE TITLE
saml2.SAMLError: Failed to parse metadata

### ISSUE THREAD

**Issue by linpy3** [abarto/flask-pysaml2-example#4]
Getting this error when using docker compose 

❯ docker compose ps
NAME                                            IMAGE                                         COMMAND                  SERVICE                 CREATED             STATUS              PORTS
flask-pysaml2-example-flask_pysaml2_example-1   flask-pysaml2-example-flask_pysaml2_example   "poetry run gunicorn…"   flask_pysaml2_example   37 minutes ago      Up 37 minutes  

metdata:

example-oktadev': {
                'entityid': 'http://flask-pysaml2-example',
                'metadata_url': 'https://dev-12345678.okta.com/app/foobar/sso/saml/metadata'
           }
     

flask-pysaml2-example-flask_pysaml2_example-1  | INFO:flask_pysaml2_example:settings: {'entityid': 'http://flask-pysaml2-example', 'metadata': {'inline': ['{"errorCode":"resource_not_found","errorSummary":"Resource not found: foobar (AppInstance)","status":404}']}, 'service': {'sp': {'endpoints': {'assertion_consumer_service': [('http://localhost:5000/auth/saml/sso/example-oktadev', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'), ('http://localhost:5000/auth/saml/sso/example-oktadev', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'), ('https://localhost:5000/auth/saml/sso/example-oktadev', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'), ('https://localhost:5000/auth/saml/sso/example-oktadev', 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST')]}, 'allow_unsolicited': True, 'authn_requests_signed': False, 'logout_requests_signed': True, 'want_assertions_signed': True, 'want_response_signed': False}}}
flask-pysaml2-example-flask_pysaml2_example-1  | ERROR:flask_pysaml2_example:Exception on /auth/saml/login/example-oktadev [GET]
flask-pysaml2-example-flask_pysaml2_example-1  | Traceback (most recent call last):
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/usr/local/lib/python3.11/xml/etree/ElementTree.py", line 1709, in feed
flask-pysaml2-example-flask_pysaml2_example-1  |     self.parser.Parse(data, False)
flask-pysaml2-example-flask_pysaml2_example-1  | xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0
flask-pysaml2-example-flask_pysaml2_example-1  | 
flask-pysaml2-example-flask_pysaml2_example-1  | During handling of the above exception, another exception occurred:
flask-pysaml2-example-flask_pysaml2_example-1  | 
flask-pysaml2-example-flask_pysaml2_example-1  | Traceback (most recent call last):
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/root/.cache/pypoetry/virtualenvs/flask-pysaml2-example-9TtSrW0h-py3.11/lib/python3.11/site-packages/saml2/mdstore.py", line 605, in parse
flask-pysaml2-example-flask_pysaml2_example-1  |     self.entities_descr = md.entities_descriptor_from_string(xmlstr)
flask-pysaml2-example-flask_pysaml2_example-1  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/root/.cache/pypoetry/virtualenvs/flask-pysaml2-example-9TtSrW0h-py3.11/lib/python3.11/site-packages/saml2/md.py", line 1824, in entities_descriptor_from_string
flask-pysaml2-example-flask_pysaml2_example-1  |     return saml2.create_class_from_xml_string(EntitiesDescriptor, xml_string)
flask-pysaml2-example-flask_pysaml2_example-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/root/.cache/pypoetry/virtualenvs/flask-pysaml2-example-9TtSrW0h-py3.11/lib/python3.11/site-packages/saml2/__init__.py", line 87, in create_class_from_xml_string
flask-pysaml2-example-flask_pysaml2_example-1  |     tree = defusedxml.ElementTree.fromstring(xml_string)
flask-pysaml2-example-flask_pysaml2_example-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/root/.cache/pypoetry/virtualenvs/flask-pysaml2-example-9TtSrW0h-py3.11/lib/python3.11/site-packages/defusedxml/common.py", line 126, in fromstring
flask-pysaml2-example-flask_pysaml2_example-1  |     parser.feed(text)
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/usr/local/lib/python3.11/xml/etree/ElementTree.py", line 1711, in feed
flask-pysaml2-example-flask_pysaml2_example-1  |     self._raiseerror(v)
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/usr/local/lib/python3.11/xml/etree/ElementTree.py", line 1618, in _raiseerror
flask-pysaml2-example-flask_pysaml2_example-1  |     raise err
flask-pysaml2-example-flask_pysaml2_example-1  | xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
flask-pysaml2-example-flask_pysaml2_example-1  | 
flask-pysaml2-example-flask_pysaml2_example-1  | The above exception was the direct cause of the following exception:
flask-pysaml2-example-flask_pysaml2_example-1  | 
flask-pysaml2-example-flask_pysaml2_example-1  | Traceback (most recent call last):
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/root/.cache/pypoetry/virtualenvs/flask-pysaml2-example-9TtSrW0h-py3.11/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
flask-pysaml2-example-flask_pysaml2_example-1  |     response = self.full_dispatch_request()
flask-pysaml2-example-flask_pysaml2_example-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/root/.cache/pypoetry/virtualenvs/flask-pysaml2-example-9TtSrW0h-py3.11/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
flask-pysaml2-example-flask_pysaml2_example-1  |     rv = self.handle_user_exception(e)
flask-pysaml2-example-flask_pysaml2_example-1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/root/.cache/pypoetry/virtualenvs/flask-pysaml2-example-9TtSrW0h-py3.11/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
flask-pysaml2-example-flask_pysaml2_example-1  |     rv = self.dispatch_request()
flask-pysaml2-example-flask_pysaml2_example-1  |          ^^^^^^^^^^^^^^^^^^^^^^^
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/root/.cache/pypoetry/virtualenvs/flask-pysaml2-example-9TtSrW0h-py3.11/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
flask-pysaml2-example-flask_pysaml2_example-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
flask-pysaml2-example-flask_pysaml2_example-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/app/flask_pysaml2_example/auth.py", line 152, in saml_login
flask-pysaml2-example-flask_pysaml2_example-1  |     saml_client = saml_client_for(idp_name)
flask-pysaml2-example-flask_pysaml2_example-1  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/app/flask_pysaml2_example/auth.py", line 82, in saml_client_for
flask-pysaml2-example-flask_pysaml2_example-1  |     saml2_config.load(settings)
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/root/.cache/pypoetry/virtualenvs/flask-pysaml2-example-9TtSrW0h-py3.11/lib/python3.11/site-packages/saml2/config.py", line 337, in load
flask-pysaml2-example-flask_pysaml2_example-1  |     self.load_complex(cnf)
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/root/.cache/pypoetry/virtualenvs/flask-pysaml2-example-9TtSrW0h-py3.11/lib/python3.11/site-packages/saml2/config.py", line 271, in load_complex
flask-pysaml2-example-flask_pysaml2_example-1  |     self.setattr("", "metadata", self.load_metadata(cnf["metadata"]))
flask-pysaml2-example-flask_pysaml2_example-1  |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/root/.cache/pypoetry/virtualenvs/flask-pysaml2-example-9TtSrW0h-py3.11/lib/python3.11/site-packages/saml2/config.py", line 391, in load_metadata
flask-pysaml2-example-flask_pysaml2_example-1  |     mds.imp(metadata_conf)
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/root/.cache/pypoetry/virtualenvs/flask-pysaml2-example-9TtSrW0h-py3.11/lib/python3.11/site-packages/saml2/mdstore.py", line 1126, in imp
flask-pysaml2-example-flask_pysaml2_example-1  |     self.load(key, val)
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/root/.cache/pypoetry/virtualenvs/flask-pysaml2-example-9TtSrW0h-py3.11/lib/python3.11/site-packages/saml2/mdstore.py", line 1100, in load
flask-pysaml2-example-flask_pysaml2_example-1  |     _md.load()
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/root/.cache/pypoetry/virtualenvs/flask-pysaml2-example-9TtSrW0h-py3.11/lib/python3.11/site-packages/saml2/mdstore.py", line 318, in load
flask-pysaml2-example-flask_pysaml2_example-1  |     self.parse(self.metadata)
flask-pysaml2-example-flask_pysaml2_example-1  |   File "/root/.cache/pypoetry/virtualenvs/flask-pysaml2-example-9TtSrW0h-py3.11/lib/python3.11/site-packages/saml2/mdstore.py", line 614, in parse
flask-pysaml2-example-flask_pysaml2_example-1  |     raise SAMLError(f"Failed to parse {_md_desc}") from e
flask-pysaml2-example-flask_pysaml2_example-1  | saml2.SAMLError: Failed to parse metadata

**Comment by linpy3** [comment]
Please ignore I have to use the right metadata
